2020-06-24 13:05:34 INFO  FileDaoImpl:21 - -3733
6ALLIKA/spring-boot-practice pull request #2
Opened 2020-06-24 10:12 UTC by 6ALLIKA

Add functionality to read the file

2020-06-24 12:30 UTC, boroda4436 commented on src/main/java/com/ma/springboot/controller/IndexController.java
> +        return fileDao.readAllLines("src/main/resources/Reviews.csv");
хардкод

2020-06-24 12:30 UTC, boroda4436 commented on src/main/java/com/ma/springboot/controller/IndexController.java
> +        return fileDao.readAllLines("src/main/resources/Reviews.csv");
заюзай аннотацію @ Value

2020-06-24 12:31 UTC, boroda4436 commented on src/main/java/com/ma/springboot/dao/impl/FileDaoImpl.java
> +public class FileDaoImpl implements FileDao {
```suggestion
public class FileReaderServiceImpl implements FileReaderService {
```

2020-06-24 12:31 UTC, boroda4436 commented on src/main/java/com/ma/springboot/dao/impl/FileDaoImpl.java
> +@Repository
```suggestion
@Service
```

2020-06-24 15:21 UTC, 6ALLIKA commented on src/main/java/com/ma/springboot/controller/IndexController.java
> +        return fileDao.readAllLines("src/main/resources/Reviews.csv");
ну да, хард код, что бы не запускать постман пока что)

2020-06-25 06:46 UTC, boroda4436 requested changes

2020-06-25 06:46 UTC, boroda4436 commented on src/main/java/com/ma/springboot/controller/IndexController.java
> +    public List<String> readLines(@Value("src/main/resources/Reviews.csv") String path) {
ну такое) Я б прибрав дефолтне значення. І змушував би користувача передавати шлях до файлу. По друге - цей функціонал не треба видивати назовні в рамках задачі. Я б прибрав його

2020-06-25 06:46 UTC, boroda4436 commented on src/main/java/com/ma/springboot/service/impl/FileReaderServiceImpl.java
> +        log.info(start - end);
Прибери зайве пліз

2020-06-25 07:02 UTC, 6ALLIKA commented on src/main/java/com/ma/springboot/service/impl/FileReaderServiceImpl.java
> +        log.info(start - end);
та я бы его убрал, это же не конечная версия)

2020-06-26 15:20 UTC, boroda4436 commented on src/test/java/com/ma/springboot/service/impl/FileReaderServiceImplTest.java
> +}
empty line

2020-06-26 15:21 UTC, boroda4436 approved these changes

2020-06-30 06:36 UTC, merged